### PR TITLE
fixing jest-cli issue and including it as a local package

### PR DESCRIPTION
**Pull request by sadiqevani**
There is an issue with tests for people who don't have `jest-cli` installed globally, so i'm including it as a dev dependency.

### CODE REVIEW

**Comment by davidyuk** [comment]
What particular issue do they have? I don't have jest installed globally, but `npm run unit` in components repository works well.

**Comment by sadiqevani** [comment]
`jest-cli` wasn't being resolved in the `node_modules` folder.

**Comment by davidyuk** [comment]
Is `npx jest` works without installing of `jest-cli`?

**Comment by sadiqevani** [comment]
@davidyuk yep works.

I'll update the npm scripts to run jest through npx

**Comment by sadiqevani** [comment]
@davidyuk seems the issue was within my `node_modules` folder, I'll close this pull-request.

**Pull request closed without merging**
