### PR TITLE
"Sandbox" Vue app for local development :) 

### PR DESCRIPTION
**Pull request by evvvritt**
`npm run dev`

- sets up a local webpack server from the /sandbox directory
- /sandbox router and components are ignored

**to do**
- figure out proper webpack setup to have index.html file inside /sandbox

### CODE REVIEW

**Comment by davidyuk** [comment]
Can't we use `vue-styleguidist` server for this purpose?

**Comment by evvvritt** [comment]
@davidyuk Ah maybe! Yeah, wasn't familiar with vue-styleguide. Though maybe a benefit of the sandbox is being able to play with different wrappers for components?

**Comment by davidyuk** [comment]
You can try any combination of components in `<componentName>.md` files, like [here](https://github.com/aeternity/aepp-components/blob/master/src/components/aeFilterList/aeFilterList.md). In local development I also connect my version of `aepp-components` to an app project by `(npm link)[https://docs.npmjs.com/cli/link]`.

**Comment by davidyuk** [comment]
Usage of `vue-styleguidist` has a downside in that some components look better when they wrapped with AeMain components, but styleguidist doesn't do it.

**Comment by evvvritt** [comment]
Ok, let's go with vue-styleguide then. If I have time I will setup and submit a new PR.

**Pull request closed without merging**
